/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package dsaproject;

import java.awt.HeadlessException;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author HOME
 */
public class accountantPanel extends javax.swing.JFrame {

    /**
     * Creates new form accountantPanel
     */
    
    Connection con = null ;
    PreparedStatement pst = null;
    ResultSet rs = null;
    
    
    public accountantPanel() {
        initComponents();
        showTableData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Id = new javax.swing.JTextField();
        fname = new javax.swing.JTextField();
        lname = new javax.swing.JTextField();
        course = new javax.swing.JTextField();
        fee = new javax.swing.JTextField();
        paid = new javax.swing.JTextField();
        due = new javax.swing.JTextField();
        address = new javax.swing.JTextField();
        city = new javax.swing.JTextField();
        contact = new javax.swing.JTextField();
        btnDelete = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnNew = new javax.swing.JButton();
        btnInsert = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8", "Title 9", "Title 10"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
            jTable1.getColumnModel().getColumn(4).setResizable(false);
            jTable1.getColumnModel().getColumn(5).setResizable(false);
            jTable1.getColumnModel().getColumn(6).setResizable(false);
            jTable1.getColumnModel().getColumn(7).setResizable(false);
            jTable1.getColumnModel().getColumn(8).setResizable(false);
            jTable1.getColumnModel().getColumn(9).setResizable(false);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 980, 250));

        Id.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Id.setOpaque(false);
        getContentPane().add(Id, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 58, 146, -1));

        fname.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        fname.setOpaque(false);
        getContentPane().add(fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(233, 58, 146, -1));

        lname.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lname.setOpaque(false);
        getContentPane().add(lname, new org.netbeans.lib.awtextra.AbsoluteConstraints(429, 58, 146, -1));

        course.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        course.setOpaque(false);
        course.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                courseActionPerformed(evt);
            }
        });
        getContentPane().add(course, new org.netbeans.lib.awtextra.AbsoluteConstraints(624, 58, 146, -1));

        fee.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        fee.setOpaque(false);
        getContentPane().add(fee, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 58, 146, -1));

        paid.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        paid.setOpaque(false);
        paid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paidActionPerformed(evt);
            }
        });
        getContentPane().add(paid, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 200, 146, -1));

        due.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        due.setOpaque(false);
        getContentPane().add(due, new org.netbeans.lib.awtextra.AbsoluteConstraints(233, 200, 146, -1));

        address.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        address.setOpaque(false);
        getContentPane().add(address, new org.netbeans.lib.awtextra.AbsoluteConstraints(428, 200, 146, -1));

        city.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        city.setOpaque(false);
        getContentPane().add(city, new org.netbeans.lib.awtextra.AbsoluteConstraints(625, 200, 146, -1));

        contact.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        contact.setOpaque(false);
        getContentPane().add(contact, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 198, 146, -1));

        btnDelete.setContentAreaFilled(false);
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(551, 331, 75, 27));

        btnUpdate.setContentAreaFilled(false);
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        getContentPane().add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(385, 331, 75, 27));

        btnNew.setContentAreaFilled(false);
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });
        getContentPane().add(btnNew, new org.netbeans.lib.awtextra.AbsoluteConstraints(717, 331, 75, 27));

        btnInsert.setContentAreaFilled(false);
        btnInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertActionPerformed(evt);
            }
        });
        getContentPane().add(btnInsert, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 331, 75, 27));

        jLabel12.setIcon(new javax.swing.ImageIcon("C:\\Users\\HOME\\Documents\\NetBeansProjects\\dsaProject\\Images\\PROJECT  DSA-05.jpg")); // NOI18N
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertActionPerformed
        // TODO add your handling code here:
        
        try {
         
            String sql = "INSERT INTO accountantpanel"
                    +"(Id, fname, lname, course, fee, paid, due, address, city, contact)"
                    + " VALUES (?,?,?,?,?,?,?,?,?,?)";
            con = DriverManager.getConnection("jdbc:mysql://localhost/accountantpanel","root","");
            pst = con.prepareStatement(sql);
            pst.setString(1,Id.getText());
            pst.setString(2,fname.getText());
            pst.setString(3,lname.getText());
            pst.setString(4,course.getText());
            pst.setString(5,fee.getText());
            pst.setString(6,paid.getText());
            pst.setString(7,due.getText());
            pst.setString(8,address.getText());
            pst.setString(9,city.getText());
            pst.setString(10,contact.getText());
            
            pst.executeUpdate();
         
            JOptionPane.showMessageDialog(rootPane, "Data Inserted Sucessfully");
           
           
            dispose();
         
         /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new accountantPanel().setVisible(true);
            }
        });
        
        
        }
        catch
        (SQLException | HeadlessException ex){
            JOptionPane.showMessageDialog(rootPane,ex );
        }
        
        
    }//GEN-LAST:event_btnInsertActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        
        
        try {
         
            String sql = " DELETE FROM accountantpanel WHERE Id=?";
            con = DriverManager.getConnection("jdbc:mysql://localhost/accountantpanel","root","");
            pst = con.prepareStatement(sql);
            pst.setString(1,Id.getText());
            pst.executeUpdate();
         
            JOptionPane.showMessageDialog(rootPane, "Data Deleted Sucessfully");
            
            dispose();
         
         /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new accountantPanel().setVisible(true);
            }
        });
         
            
            
            
        }
        catch
        (SQLException | HeadlessException ex){
            JOptionPane.showMessageDialog(rootPane,ex );
        }
        
        
        
        
        
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        
           try {
         
            String sql = "UPDATE accountantpanel SET fname=?,lname=?,course=?,fee=?,paid=?,due=?,address=?,city=?,contact=? WHERE Id=?";
            con = DriverManager.getConnection("jdbc:mysql://localhost/accountantpanel","root","");
            pst = con.prepareStatement(sql);
            
            
            pst.setString(1,fname.getText());
            pst.setString(2,lname.getText());
            pst.setString(3,course.getText());
            pst.setString(4,fee.getText());
            pst.setString(5,paid.getText());
            pst.setString(6,due.getText());
            pst.setString(7,address.getText());
            pst.setString(8,city.getText());
            pst.setString(9,contact.getText());
            pst.setString(10,Id.getText());
            
            pst.executeUpdate();
         
            JOptionPane.showMessageDialog(rootPane, "Data Updated Sucessfully");
            
            
            dispose();
         
         /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new accountantPanel().setVisible(true);
            }
        });
           
        }
        catch
        (SQLException | HeadlessException ex){
            JOptionPane.showMessageDialog(rootPane,ex );
        }
       
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
        // TODO add your handling code here:
        
        dispose();
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new loginSelector().setVisible(true);
            }
        });
        
        
    }//GEN-LAST:event_btnNewActionPerformed

    private void courseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_courseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_courseActionPerformed

    private void paidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_paidActionPerformed

        
      public void showTableData(){
      
      
          try {
            con = DriverManager.getConnection("jdbc:mysql://localhost/accountantpanel","root","");
            String sql = "SELECT * FROM accountantpanel";
            pst = con.prepareStatement(sql);
            rs=pst.executeQuery();
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
              
              
              
              
          } 
          catch (SQLException e) 
          {
              JOptionPane.showMessageDialog(rootPane, e);
          }
       
         
         
       }  
        
      
      
        
        
        /*/*/
            
   
       public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(loginSelection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(loginSelection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(loginSelection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(loginSelection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new accountantPanel().setVisible(true);
            }
        });
    }      
            

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Id;
    private javax.swing.JTextField address;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnInsert;
    private javax.swing.JButton btnNew;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JTextField city;
    private javax.swing.JTextField contact;
    private javax.swing.JTextField course;
    private javax.swing.JTextField due;
    private javax.swing.JTextField fee;
    private javax.swing.JTextField fname;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField lname;
    private javax.swing.JTextField paid;
    // End of variables declaration//GEN-END:variables
}
